# Generated by Django 5.0.6 on 2024-06-22 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glish', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='level',
            name='desc',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='module',
            name='desc',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='moduleelement',
            name='desc',
            field=models.TextField(blank=True, null=True),
        ),
    ]
